name: GitHub Actions Build UAS-PCC-RIZQI-2025
run-name: ${{ github.actor }} is Building Docker Image 🚀
on: [push]
jobs:
  Build-Docker-Image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Verify Dockerfile exists
        run: ls -la

      - name: login and build
        run: |
          docker build -t mrizqiis/uas-pcc-mrizqiis-2025:latest -f Dockerfile .
          echo ${{ secrets.DOCKERHUB_ACCESSTOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker push mrizqiis/uas-pcc-mrizqiis-2025:latest